server:
  port:
    10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
zuul:
  prefix: /api
  routes:
    item-service: /item/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  connectTimeout: 1000
  ReadTimeout: 3500
  MaxAutoRetries: 0
  MaxAutoREtiesNextServer: 0